import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GiCrystalBall } from "react-icons/gi";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} dark:bg-stone-800`}
			>
				<Header
					showLogo
					mainNavigation={[
						{
							id: "card-database",
							content: (
								<Link href="/cards">
                  Database
								</Link>
							),
						},
					]}
				/>
				{children}
			</body>
		</html>
	);
}
