/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsSetCollectorNumberLangRouteImport } from './routes/cards/$set.$collectorNumber.$lang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSetCollectorNumberLangRoute =
  CardsSetCollectorNumberLangRouteImport.update({
    id: '/cards/$set/$collectorNumber/$lang',
    path: '/cards/$set/$collectorNumber/$lang',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards/$set/$collectorNumber/$lang': typeof CardsSetCollectorNumberLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards/$set/$collectorNumber/$lang': typeof CardsSetCollectorNumberLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards/$set/$collectorNumber/$lang': typeof CardsSetCollectorNumberLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cards/$set/$collectorNumber/$lang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards/$set/$collectorNumber/$lang'
  id: '__root__' | '/' | '/cards/$set/$collectorNumber/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsSetCollectorNumberLangRoute: typeof CardsSetCollectorNumberLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$set/$collectorNumber/$lang': {
      id: '/cards/$set/$collectorNumber/$lang'
      path: '/cards/$set/$collectorNumber/$lang'
      fullPath: '/cards/$set/$collectorNumber/$lang'
      preLoaderRoute: typeof CardsSetCollectorNumberLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsSetCollectorNumberLangRoute: CardsSetCollectorNumberLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
